### ISSUE TITLE
Reference genome variable in prep_genome_lib.pl seems incorrect.

### ISSUE THREAD

**Issue by seversond12** [FusionFilter/FusionFilter#1]
Hello, 

I'm concerned that when I ran:  

perl ~/STAR/FusionFilter-master/prep_genome_lib.pl --genome_fa /mnt/lustre/data/hg19/Viral_adjuncts/hg19_NC001526_NC007605.fa --gtf /mnt/lustre/data/hg19/Viral_adjuncts/hg19_NC001526_NC007605.STARFUS.new_annotated.gtf --blast_pairs blast_pairs.gene_syms.outfmt6.gz --cdna_fa cDNA_seqs.masked.fa

I received an error in the output when the script attempted to run STAR.
- Running CMD: STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa.star.idx  --twopassMode Basic  --genomeFastaFiles /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa  --limitGenomeGenerateRAM 40419136213  --sjdbGTFfile /mnt/lustre/data/hg19/Viral_adjuncts/hg19_NC001526_NC007605.STARFUS.new_annotated.gtf  --sjdbOverhang 100 
  Oct 29 17:34:52 ..... Started STAR run
  Oct 29 17:34:52 ... Starting to generate Genome files

EXITING because of INPUT ERROR: could not open genomeFastaFile: /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa

Now I could have renamed my reference genome fasta file to fit the expected value (ref_genome.fa) and moved it to the target directory as the script seems to expect, but felt I didn't want to hack it as I have several genomes to index for use with STAR-Fusion. Instead, I took a look in your script and found that instead of feeding STAR the variable displayed in the option, it list instructed STAR on line 148 to 

  $cmd = "STAR --runThreadN $CPU --runMode genomeGenerate --genomeDir $star_index "
            . " --twopassMode Basic "
            . " --genomeFastaFiles $output_dir/ref_genome.fa"
            . " --limitGenomeGenerateRAM 40419136213 "
            . " --sjdbGTFfile $gtf_file "
            . " --sjdbOverhang 100 ";

I have changed this to:

  $cmd = "STAR --runThreadN $CPU --runMode genomeGenerate --genomeDir $star_index "
            . " --twopassMode Basic "
            . " --genomeFastaFiles $genome_fa_file"
            . " --limitGenomeGenerateRAM 40419136213 "
            . " --sjdbGTFfile $gtf_file "
            . " --sjdbOverhang 100 ";

I would like to know if this change makes sense, or if I have misinterpreted your intention and there is some file ref_genome.fa that I am meant to have generated during the index generation process that I have missed or that it should be the masked cDNA fasta file! I would also like to note on line 142 that you have 

 my $star_index = "$output_dir/ref_genome.fa.star.idx";

And I was curious if this was also meant to be 

my $ref_name = base_name($genome_fa_file) ##from the File::Basename module
 my $star_index = "$output_dir/$ref_name.star.idx";

I would appreciate if you could let me know if I've misinterpreted how the code should be, so that I don't proceed with something non-sensical! 

Warm regards,
David Severson

**Comment by brianjohnhaas** [comment]
Hi David,

Earlier in the script, it's supposed to create a symlink called
'ref_genome.fa' in the output directory that points to your target genome
fasta file.

Is there no symlink at:
 /mnt/lustre/data/hg19/STARindex_hg19_NC001526_
NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa

or is it broken?

best,

~brian

On Thu, Oct 29, 2015 at 1:59 PM, seversond12 notifications@github.com
wrote:

> Hello,
> 
> I'm concerned that when I ran:
> 
> perl ~/STAR/FusionFilter-master/prep_genome_lib.pl --genome_fa
> /mnt/lustre/data/hg19/Viral_adjuncts/hg19_NC001526_NC007605.fa --gtf
> /mnt/lustre/data/hg19/Viral_adjuncts/hg19_NC001526_NC007605.STARFUS.new_annotated.gtf
> --blast_pairs blast_pairs.gene_syms.outfmt6.gz --cdna_fa cDNA_seqs.masked.fa
> 
> I received an error in the output when the script attempted to run STAR.
> - Running CMD: STAR --runThreadN 4 --runMode genomeGenerate
>   --genomeDir
>   /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa.star.idx
>   --twopassMode Basic --genomeFastaFiles
>   /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa
>   --limitGenomeGenerateRAM 40419136213 --sjdbGTFfile
>   /mnt/lustre/data/hg19/Viral_adjuncts/hg19_NC001526_NC007605.STARFUS.new_annotated.gtf
>   --sjdbOverhang 100 Oct 29 17:34:52 ..... Started STAR run Oct 29 17:34:52
>   ... Starting to generate Genome files
> 
> EXITING because of INPUT ERROR: could not open genomeFastaFile:
> /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/ref_genome.fa
> 
> Now I could have renamed my reference genome fasta file to fit the
> expected value (ref_genome.fa) and moved it to the target directory as the
> script seems to expect, but felt I didn't want to hack it as I have several
> genomes to index for use with STAR-Fusion. Instead, I took a look in your
> script and found that instead of feeding STAR the variable displayed in the
> option, it list instructed STAR on line 148 to
> 
> $cmd = "STAR --runThreadN $CPU --runMode genomeGenerate --genomeDir
> $star_index "
> . " --twopassMode Basic "
> . " --genomeFastaFiles $output_dir/ref_genome.fa"
> . " --limitGenomeGenerateRAM 40419136213 "
> . " --sjdbGTFfile $gtf_file "
> . " --sjdbOverhang 100 ";
> 
> I have changed this to:
> 
> $cmd = "STAR --runThreadN $CPU --runMode genomeGenerate --genomeDir
> $star_index "
> . " --twopassMode Basic "
> . " --genomeFastaFiles $genome_fa_file"
> . " --limitGenomeGenerateRAM 40419136213 "
> . " --sjdbGTFfile $gtf_file "
> . " --sjdbOverhang 100 ";
> 
> I would like to know if this change makes sense, or if I have
> misinterpreted your intention and there is some file ref_genome.fa that I
> am meant to have generated during the index generation process that I have
> missed or that it should be the masked cDNA fasta file! I would also like
> to note on line 142 that you have
> 
> my $star_index = "$output_dir/ref_genome.fa.star.idx";
> 
> And I was curious if this was also meant to be
> 
> my $ref_name = base_name($genome_fa_file) ##from the File::Basename module
> my $star_index = "$output_dir/$ref_name.star.idx";
> 
> I would appreciate if you could let me know if I've misinterpreted how the
> code should be, so that I don't proceed with something non-sensical!
> 
> Warm regards,
> David Severson
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FusionFilter/FusionFilter/issues/1.

## 

## 

Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas http://broad.mit.edu/~bhaas

**Comment by seversond12** [comment]
Hello Brian,

Ah, it's behaving funny for some reason... it created a symlink, but the symlink is not exactly right and flashes red on the screen...

[dseverson@login1(cortex) STAR_Fusion_ref]$ ls -lha
lrwxrwxrwx 1 dseverson users  120 Oct 29 17:29 ref_genome.fa -> /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/../../hg19_NC001526_NC007605

I suppose it's broken for some reason, but I have no idea why this could be. I should say I initially executed the script with

--genome_fa ../../hg19_NC_001526_NC007605.fa 

and then changed it to the explicit path posted above after a run was aborted due to the failure of the --twopassmode parameter because I  accidentally had an older version of STAR in my path. 

It looks like it concatenated the two, but I have no idea why it would do that after an aborted attempt to run the script. That said I don't use symlinks as often as I should.

I'll see if I can't get it to work as originally written by removing the symlink and trying again.

**Comment by brianjohnhaas** [comment]
Hopefully it works after removing the bad symlink.

best,

~b

On Thu, Oct 29, 2015 at 3:52 PM, David T. Severson <notifications@github.com

> wrote:
> 
> Ah, it's behaving funny for some reason... it created a symlink, but the
> symlink is not exactly right and flashes red on the screen...
> 
> [dseverson@login1(cortex) STAR_Fusion_ref]$ ls -lha
> lrwxrwxrwx 1 dseverson users 120 Oct 29 17:29 ref_genome.fa ->
> /mnt/lustre/data/hg19/STARindex_hg19_NC001526_NC007605_new_annotated_75over/STAR_Fusion_ref/../../hg19_NC001526_NC007605
> 
> I suppose it's broken for some reason, but I have no idea why this could
> be. I should say I initially executed the script with
> 
> --genome_fa ../../hg19_NC_001526_NC007605.fa
> 
> and then changed it to the explicit path posted above after a run was
> aborted due to the failure of the --twopassmode parameter because I
> accidentally had an older version of STAR in my path.
> 
> It looks like it concatenated the two, but I have no idea why it would do
> that after an aborted attempt to run the script. That said I don't use
> symlinks as often as I should.
> 
> I'll see if I can't get it to work as originally written by removing the
> symlink and trying again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FusionFilter/FusionFilter/issues/1#issuecomment-152300339
> .

## 

## 

Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas http://broad.mit.edu/~bhaas
